/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visuales;

import classes.Rubro;
import classes.Supermercado;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emadupre
 */
public class DeTodoSA extends javax.swing.JFrame {
    
    public static Supermercado supermercado = new Supermercado();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeTodoSA.class.getName());

    /**
     * Creates new form A
     */

    public static void rellenarComboBox(JComboBox box){
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) box.getModel();
        Rubro[] lista = Rubro.values();
        for(int i = 0; i < lista.length; i++){
            modelo.addElement(lista[i].toString());
        }
    }
    
    public static void rellenarCabecerasTablas(JTable tabla){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Categoría");
        modelo.addColumn("Stock");
        tabla.setModel(modelo);
    }
    
    public DeTodoSA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuGestion = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        gestionProductos = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        consultaPorNombre = new javax.swing.JCheckBoxMenuItem();
        consultaPorPrecio = new javax.swing.JCheckBoxMenuItem();
        consultaPorRubro = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        menuAdministracion.setText("Administracion");

        gestionProductos.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        gestionProductos.setText("Gestion de Productos");
        gestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionProductosActionPerformed(evt);
            }
        });
        menuAdministracion.add(gestionProductos);

        menuGestion.add(menuAdministracion);

        menuConsultas.setText("Consultas");

        consultaPorNombre.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        consultaPorNombre.setText("Consulta por Nombre");
        consultaPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPorNombreActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaPorNombre);

        consultaPorPrecio.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        consultaPorPrecio.setText("Consulta por Precio");
        consultaPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPorPrecioActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaPorPrecio);

        consultaPorRubro.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        consultaPorRubro.setText("Consulta por Rubro");
        consultaPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPorRubroActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaPorRubro);

        menuGestion.add(menuConsultas);

        setJMenuBar(menuGestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionProductosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        gestionDeProductos gestor = new gestionDeProductos(DeTodoSA.supermercado);
        escritorio.add(gestor);
        gestor.setVisible(true);
        escritorio.moveToFront(gestor);
    }//GEN-LAST:event_gestionProductosActionPerformed

    private void consultaPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPorNombreActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        consultaPorNombre consultaPorNombre = new consultaPorNombre();
        consultaPorNombre.setVisible(true);
        escritorio.add(consultaPorNombre);
        escritorio.moveToFront(consultaPorNombre);
    }//GEN-LAST:event_consultaPorNombreActionPerformed

    private void consultaPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPorPrecioActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        consultaPorPrecio consultaPorPrecio = new consultaPorPrecio(supermercado);
        consultaPorPrecio.setVisible(true);
        escritorio.add(consultaPorPrecio);
        escritorio.moveToFront(consultaPorPrecio);
    }//GEN-LAST:event_consultaPorPrecioActionPerformed

    private void consultaPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPorRubroActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        consultaPorRubro consultaPorRubro = new consultaPorRubro();
        consultaPorRubro.setVisible(true);
        escritorio.add(consultaPorRubro);
        escritorio.moveToFront(consultaPorRubro);
    }//GEN-LAST:event_consultaPorRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeTodoSA().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem consultaPorNombre;
    private javax.swing.JCheckBoxMenuItem consultaPorPrecio;
    private javax.swing.JCheckBoxMenuItem consultaPorRubro;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem gestionProductos;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuBar menuGestion;
    // End of variables declaration//GEN-END:variables
}
